repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: check-shebang-scripts-are-executable
    -   id: end-of-file-fixer
        exclude: ^\.(idea|vscode)/.*
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
        args: ["--external-sources"]
